"""
Reproduces the severity-grid ECE curve (Table 1 in the paper, plotted as a
curve) directly from results/cgt_tta_results_cifar10.csv — no hardcoded
numbers, so this stays correct if the CSV is regenerated by
scripts/cifar10c_severity_sweep.py.
"""
import pandas as pd
import matplotlib.pyplot as plt

RESULTS_CSV = "../results/cgt_tta_results_cifar10.csv"

LABELS = {
    "source": "Source Only",
    "tent": "TENT",
    "eata": "EATA",
    "sar": "SAR",
    "tent_temp": "TENT + Temp. Scaling",
    "sicl": "SICL (reproduced)",
    "cgt_isocal": "IsoCal (flip signal)",
    "sicl_isocal": "IsoCal-TTA (Ours)",
}
COLORS = {
    "source": "#888888",
    "tent": "#4c72b0",
    "eata": "#8fd3e8",
    "sar": "#8c8c00",
    "tent_temp": "#dd8452",
    "sicl": "#8172b2",
    "cgt_isocal": "#55a868",
    "sicl_isocal": "#c44e52",
}
ORDER = ["source", "eata", "sar", "tent", "cgt_isocal", "tent_temp", "sicl", "sicl_isocal"]

def main():
    df = pd.read_csv(RESULTS_CSV)
    pivot = df.groupby(["mode", "severity"])["ece"].mean().unstack()

    fig, ax = plt.subplots(figsize=(7, 5))
    for mode in ORDER:
        if mode not in pivot.index:
            continue
        style = dict(color=COLORS[mode], marker="o", linewidth=2.5 if mode == "sicl_isocal" else 1.5)
        if mode == "source":
            style.update(linestyle="--", marker="o", color="#888888")
        ax.plot(pivot.columns, pivot.loc[mode], label=LABELS[mode], **style)

    ax.set_xlabel("Corruption Severity")
    ax.set_ylabel("Expected Calibration Error (%)")
    ax.set_title("CIFAR-10-C: Calibration Error by Severity")
    ax.set_xticks(pivot.columns)
    ax.legend(loc="upper left", fontsize=9, frameon=False)
    ax.spines[["top", "right"]].set_visible(False)
    fig.tight_layout()
    fig.savefig("isocal_tta_severity_curve.png", dpi=200)
    print("Saved isocal_tta_severity_curve.png")

if __name__ == "__main__":
    main()
